DROP VIEW IF EXISTS learner_view;
CREATE VIEW learner_view AS
SELECT ssn, last_name, first_name, gender, dob, phone_number, address, password_user, email
FROM user_system
JOIN learner
ON learner.id = user_system.id
WITH LOCAL CHECK OPTION;

DROP VIEW IF EXISTS lecturer_view;
CREATE VIEW lecturer_view AS
SELECT ssn, last_name, first_name, gender, dob, phone_number, address, password_user, email
FROM user_system
JOIN lecturer
ON lecturer.id = user_system.id
WITH LOCAL CHECK OPTION;

DROP VIEW IF EXISTS supporter_view;
CREATE VIEW supporter_view AS
SELECT ssn, last_name, first_name, gender, dob, phone_number, address, password_user, email
FROM user_system
JOIN supporter
ON supporter.id = user_system.id
WITH LOCAL CHECK OPTION;

CREATE ROLE IF NOT EXISTS `learner_role`@`localhost`;

GRANT SELECT, UPDATE, DELETE ON education_registration.learner_view TO `learner_role`;
GRANT SELECT ON education_registration.lecturer_view TO `learner_role`;
GRANT SELECT ON education_registration.field to `learner_role`;
GRANT SELECT ON education_registration.course to `learner_role`;
GRANT SELECT ON education_registration.documents to `learner_role`;
GRANT SELECT ON education_registration.test to `learner_role`;
GRANT SELECT ON education_registration.prerequires to `learner_role`;
GRANT SELECT ON education_registration.takes to `learner_role`;
GRANT SELECT ON education_registration.degree to `learner_role`;
GRANT SELECT ON education_registration.teaches to `learner_role`;
GRANT SELECT, INSERT, DELETE, UPDATE ON education_registration.enrolls to `learner_role`;
GRANT SELECT, INSERT, DELETE, UPDATE ON education_registration.enrolls_info to `learner_role`;
GRANT SELECT, INSERT, DELETE, UPDATE ON education_registration.details_rates to `learner_role`;
GRANT SELECT ON education_registration.supporter_view TO `learner_role`;                 


CREATE ROLE IF NOT EXISTS `lecturer_role`@`localhost`;
GRANT SELECT, UPDATE, DELETE ON education_registration.lecturer_view TO `lecturer_role`;
GRANT SELECT ON education_registration.learner_view TO `lecturer_role`;
GRANT SELECT, UPDATE, INSERT, DELETE ON education_registration.course to `lecturer_role`;
GRANT SELECT, UPDATE, INSERT, DELETE ON education_registration.field to `lecturer_role`;
GRANT SELECT, UPDATE, INSERT, DELETE ON education_registration.documents to `lecturer_role`;
GRANT SELECT, UPDATE, INSERT, DELETE ON education_registration.test to `lecturer_role`;
GRANT SELECT, UPDATE, INSERT, DELETE ON education_registration.takes to `lecturer_role`;
GRANT SELECT ON education_registration.enrolls_info TO `lecturer_role`;
GRANT SELECT ON education_registration.details_rates to `lecturer_role`;
GRANT SELECT, INSERT, DELETE, UPDATE ON education_registration.prerequires TO `lecturer_role`;
GRANT SELECT, INSERT, DELETE, UPDATE ON education_registration.course_in_field TO `lecturer_role`;
GRANT SELECT, INSERT, DELETE, UPDATE ON education_registration.degree TO `lecturer_role`;
GRANT SELECT, INSERT, DELETE, UPDATE ON education_registration.prerequires TO `lecturer_role`;
GRANT SELECT, INSERT, DELETE, UPDATE ON education_registration.teaches TO `lecturer_role`;
GRANT SELECT ON education_registration.supporter_view to `lecturer_role`;

CREATE ROLE IF NOT EXISTS `supporter_role`@`localhost`;
GRANT All PRIVILEGES ON education_registration.* TO `supporter_role`;

-- create user and grant role
CREATE USER `minh.buikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `minh.buikim@gmail.com`@`localhost` ;
CREATE USER `thu.buithi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `thu.buithi@gmail.com`@`localhost` ;
CREATE USER `anh.buituan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `anh.buituan@gmail.com`@`localhost` ;
CREATE USER `thanh.buixuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `thanh.buixuan@gmail.com`@`localhost` ;
CREATE USER `hien.caophamthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hien.caophamthanh@gmail.com`@`localhost` ;
CREATE USER `ngan.caothihai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `ngan.caothihai@gmail.com`@`localhost` ;
CREATE USER `guan.chaiyeong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `guan.chaiyeong@gmail.com`@`localhost` ;
CREATE USER `thanh.chaudai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `thanh.chaudai@gmail.com`@`localhost` ;
CREATE USER `truc.danghoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `truc.danghoang@gmail.com`@`localhost` ;
CREATE USER `hanh.dangthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hanh.dangthimy@gmail.com`@`localhost` ;
CREATE USER `du.daocao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `du.daocao@gmail.com`@`localhost` ;
CREATE USER `hai.daothien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hai.daothien@gmail.com`@`localhost` ;
CREATE USER `phong.dinhtran@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `phong.dinhtran@gmail.com`@`localhost` ;
CREATE USER `nam.dohoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `nam.dohoang@gmail.com`@`localhost` ;
CREATE USER `nguyen.dongocthao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `nguyen.dongocthao@gmail.com`@`localhost` ;
CREATE USER `khuyen.dothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `khuyen.dothi@gmail.com`@`localhost` ;
CREATE USER `ngan.dothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `ngan.dothi@gmail.com`@`localhost` ;
CREATE USER `van.doanthituyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `van.doanthituyet@gmail.com`@`localhost` ;
CREATE USER `truong.doanxuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `truong.doanxuan@gmail.com`@`localhost` ;
CREATE USER `cuong.duongquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `cuong.duongquoc@gmail.com`@`localhost` ;
CREATE USER `thuan.hodang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `thuan.hodang@gmail.com`@`localhost` ;
CREATE USER `hao.hohuu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hao.hohuu@gmail.com`@`localhost` ;
CREATE USER `thanh.hothithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `thanh.hothithu@gmail.com`@`localhost` ;
CREATE USER `trinh.hoangnukieu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `trinh.hoangnukieu@gmail.com`@`localhost` ;
CREATE USER `anh.hoangquynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `anh.hoangquynh@gmail.com`@`localhost` ;
CREATE USER `tung.hoangthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `tung.hoangthanh@gmail.com`@`localhost` ;
CREATE USER `sinh.huadieptruong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `sinh.huadieptruong@gmail.com`@`localhost` ;
CREATE USER `tat.huynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `tat.huynh@gmail.com`@`localhost` ;
CREATE USER `nghia.huynhngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `nghia.huynhngoc@gmail.com`@`localhost` ;
CREATE USER `hung.huynhnhat@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hung.huynhnhat@gmail.com`@`localhost` ;
CREATE USER `sac.huynhtang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `sac.huynhtang@gmail.com`@`localhost` ;
CREATE USER `dung.huynhthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `dung.huynhthanh@gmail.com`@`localhost` ;
CREATE USER `diep.huynhthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `diep.huynhthi@gmail.com`@`localhost` ;
CREATE USER `nga.huynhthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `nga.huynhthi@gmail.com`@`localhost` ;
CREATE USER `to.huynhthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `to.huynhthi@gmail.com`@`localhost` ;
CREATE USER `thuy.huynhthicam@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `thuy.huynhthicam@gmail.com`@`localhost` ;
CREATE USER `lan.huynhvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `lan.huynhvan@gmail.com`@`localhost` ;
CREATE USER `minh.huynhvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `minh.huynhvan@gmail.com`@`localhost` ;
CREATE USER `trang.khauthiyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `trang.khauthiyen@gmail.com`@`localhost` ;
CREATE USER `tuyet.lamnhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `tuyet.lamnhu@gmail.com`@`localhost` ;
CREATE USER `phuong.lemy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `phuong.lemy@gmail.com`@`localhost` ;
CREATE USER `danh.lethanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `danh.lethanh@gmail.com`@`localhost` ;
CREATE USER `ty.lethihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `ty.lethihong@gmail.com`@`localhost` ;
CREATE USER `hoa.luongthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hoa.luongthi@gmail.com`@`localhost` ;
CREATE USER `dung.lyanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `dung.lyanh@gmail.com`@`localhost` ;
CREATE USER `lam.lyson@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `lam.lyson@gmail.com`@`localhost` ;
CREATE USER `koko.mady@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `koko.mady@gmail.com`@`localhost` ;
CREATE USER `nguyen.ngohuynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `nguyen.ngohuynh@gmail.com`@`localhost` ;
CREATE USER `dung.ngoquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `dung.ngoquang@gmail.com`@`localhost` ;
CREATE USER `vinh.ngothe@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `vinh.ngothe@gmail.com`@`localhost` ;
CREATE USER `trong.nguyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `trong.nguyen@gmail.com`@`localhost` ;
CREATE USER `ninh.nguyendoan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `ninh.nguyendoan@gmail.com`@`localhost` ;
CREATE USER `duong.nguyenduc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `duong.nguyenduc@gmail.com`@`localhost` ;
CREATE USER `uyen.nguyengiamai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `uyen.nguyengiamai@gmail.com`@`localhost` ;
CREATE USER `duy.nguyenhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `duy.nguyenhoang@gmail.com`@`localhost` ;
CREATE USER `nam.nguyenhong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `nam.nguyenhong@gmail.com`@`localhost` ;
CREATE USER `cuong.nguyenhung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `cuong.nguyenhung@gmail.com`@`localhost` ;
CREATE USER `ngan.nguyenkim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `ngan.nguyenkim@gmail.com`@`localhost` ;
CREATE USER `hunh.nguyenmanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hunh.nguyenmanh@gmail.com`@`localhost` ;
CREATE USER `duc.nguyenminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `duc.nguyenminh@gmail.com`@`localhost` ;
CREATE USER `quang.nguyenminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `quang.nguyenminh@gmail.com`@`localhost` ;
CREATE USER `thuan.nguyenminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `thuan.nguyenminh@gmail.com`@`localhost` ;
CREATE USER `thuc.nguyenminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `thuc.nguyenminh@gmail.com`@`localhost` ;
CREATE USER `hoa.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hoa.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER `qui.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `qui.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER `long.nguyenphi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `long.nguyenphi@gmail.com`@`localhost` ;
CREATE USER `thao.nguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `thao.nguyenthanh@gmail.com`@`localhost` ;
CREATE USER `tung.nguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `tung.nguyenthanh@gmail.com`@`localhost` ;
CREATE USER `long.nguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `long.nguyenthanh@gmail.com`@`localhost` ;
CREATE USER `dung.nguyenthe@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `dung.nguyenthe@gmail.com`@`localhost` ;
CREATE USER `an.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `an.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `diem.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `diem.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `ha.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `ha.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `linh.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `linh.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `luan.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `luan.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `man.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `man.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `nguyet.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `nguyet.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `oanh.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `oanh.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `thuy.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `thuy.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `dao.nguyenthianh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `dao.nguyenthianh@gmail.com`@`localhost` ;
CREATE USER `hoa.nguyenthicong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hoa.nguyenthicong@gmail.com`@`localhost` ;
CREATE USER `dieu.nguyenthihanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `dieu.nguyenthihanh@gmail.com`@`localhost` ;
CREATE USER `ly.nguyenthihoai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `ly.nguyenthihoai@gmail.com`@`localhost` ;
CREATE USER `huong.nguyenthihoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `huong.nguyenthihoang@gmail.com`@`localhost` ;
CREATE USER `dung.nguyenthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `dung.nguyenthikim@gmail.com`@`localhost` ;
CREATE USER `phuong.nguyenthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `phuong.nguyenthikim@gmail.com`@`localhost` ;
CREATE USER `oanh.nguyenthile@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `oanh.nguyenthile@gmail.com`@`localhost` ;
CREATE USER `ly.nguyenthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `ly.nguyenthimy@gmail.com`@`localhost` ;
CREATE USER `bang.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `bang.nguyenthingoc@gmail.com`@`localhost` ;
CREATE USER `em.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `em.nguyenthingoc@gmail.com`@`localhost` ;
CREATE USER `tuyet.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `tuyet.nguyenthingoc@gmail.com`@`localhost` ;
CREATE USER `hien.nguyenthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hien.nguyenthithu@gmail.com`@`localhost` ;
CREATE USER `thao.nguyenthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `thao.nguyenthithu@gmail.com`@`localhost` ;
CREATE USER `trang.nguyenthithuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `trang.nguyenthithuy@gmail.com`@`localhost` ;
CREATE USER `mai.nguyenthituyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `mai.nguyenthituyet@gmail.com`@`localhost` ;
CREATE USER `hien.nguyenthuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hien.nguyenthuong@gmail.com`@`localhost` ;
CREATE USER `lam.nguyentung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `lam.nguyentung@gmail.com`@`localhost` ;
CREATE USER `vy.nguyentuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `vy.nguyentuong@gmail.com`@`localhost` ;
CREATE USER `bay.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `bay.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `cam.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `cam.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `canh.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `canh.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `ha.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `ha.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `hien.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hien.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `tan.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `tan.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `tho.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `tho.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `tien.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `tien.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `cuong.nguyenviet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `cuong.nguyenviet@gmail.com`@`localhost` ;
CREATE USER `hieu.nuyenthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hieu.nuyenthihong@gmail.com`@`localhost` ;
CREATE USER `vuong.pham@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `vuong.pham@gmail.com`@`localhost` ;
CREATE USER `phong.phamduy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `phong.phamduy@gmail.com`@`localhost` ;
CREATE USER `linh.phamhoaikhanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `linh.phamhoaikhanh@gmail.com`@`localhost` ;
CREATE USER `khanh.phamhong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `khanh.phamhong@gmail.com`@`localhost` ;
CREATE USER `khoi.phammanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `khoi.phammanh@gmail.com`@`localhost` ;
CREATE USER `son.phamngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `son.phamngoc@gmail.com`@`localhost` ;
CREATE USER `luat.phamquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `luat.phamquang@gmail.com`@`localhost` ;
CREATE USER `oanh.phamthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `oanh.phamthi@gmail.com`@`localhost` ;
CREATE USER `xuan.phamthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `xuan.phamthi@gmail.com`@`localhost` ;
CREATE USER `loan.phamthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `loan.phamthihong@gmail.com`@`localhost` ;
CREATE USER `hanh.phamthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hanh.phamthithu@gmail.com`@`localhost` ;
CREATE USER `loan.phamthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `loan.phamthithu@gmail.com`@`localhost` ;
CREATE USER `dao.phamthitruc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `dao.phamthitruc@gmail.com`@`localhost` ;
CREATE USER `anh.phanhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `anh.phanhoang@gmail.com`@`localhost` ;
CREATE USER `phong.phanthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `phong.phanthithu@gmail.com`@`localhost` ;
CREATE USER `hau.phantrung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hau.phantrung@gmail.com`@`localhost` ;
CREATE USER `hieu.phanvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hieu.phanvan@gmail.com`@`localhost` ;
CREATE USER `long.phunghoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `long.phunghoang@gmail.com`@`localhost` ;
CREATE USER `nguyen.phuongcao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `nguyen.phuongcao@gmail.com`@`localhost` ;
CREATE USER `trang.tannhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `trang.tannhu@gmail.com`@`localhost` ;
CREATE USER `hue.tongthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hue.tongthi@gmail.com`@`localhost` ;
CREATE USER `ngoc.tranbao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `ngoc.tranbao@gmail.com`@`localhost` ;
CREATE USER `sang.tranbao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `sang.tranbao@gmail.com`@`localhost` ;
CREATE USER `hung.trancong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hung.trancong@gmail.com`@`localhost` ;
CREATE USER `chien.trandinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `chien.trandinh@gmail.com`@`localhost` ;
CREATE USER `duong.trandinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `duong.trandinh@gmail.com`@`localhost` ;
CREATE USER `tri.tranhuu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `tri.tranhuu@gmail.com`@`localhost` ;
CREATE USER `vuong.trankim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `vuong.trankim@gmail.com`@`localhost` ;
CREATE USER `ngan.tranngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `ngan.tranngoc@gmail.com`@`localhost` ;
CREATE USER `van.trannhat@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `van.trannhat@gmail.com`@`localhost` ;
CREATE USER `triet.tranongminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `triet.tranongminh@gmail.com`@`localhost` ;
CREATE USER `ha.tranphamthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `ha.tranphamthanh@gmail.com`@`localhost` ;
CREATE USER `linh.tranquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `linh.tranquoc@gmail.com`@`localhost` ;
CREATE USER `bup.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `bup.tranthi@gmail.com`@`localhost` ;
CREATE USER `hien.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hien.tranthi@gmail.com`@`localhost` ;
CREATE USER `thu.tranthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `thu.tranthihong@gmail.com`@`localhost` ;
CREATE USER `hoa.tranthoai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `hoa.tranthoai@gmail.com`@`localhost` ;
CREATE USER `anh.trantuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `anh.trantuan@gmail.com`@`localhost` ;
CREATE USER `nhat.tranvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `nhat.tranvan@gmail.com`@`localhost` ;
CREATE USER `trinh\.truongquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `trinh\.truongquang@gmail.com`@`localhost` ;
CREATE USER `that.truongthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `that.truongthi@gmail.com`@`localhost` ;
CREATE USER `dung.truongtien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `lecturer_role` TO `dung.truongtien@gmail.com`@`localhost` ;

-- create account for learner

CREATE USER `son.buidai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `son.buidai@gmail.com`@`localhost` ;
CREATE USER `nam.buithihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `nam.buithihong@gmail.com`@`localhost` ;
CREATE USER `duong.buithithuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `duong.buithithuy@gmail.com`@`localhost` ;
CREATE USER `mai.buithitruc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `mai.buithitruc@gmail.com`@`localhost` ;
CREATE USER `trinh.buithituyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `trinh.buithituyet@gmail.com`@`localhost` ;
CREATE USER `ky.buitrung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `ky.buitrung@gmail.com`@`localhost` ;
CREATE USER `kiet.buituan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `kiet.buituan@gmail.com`@`localhost` ;
CREATE USER `hien.buivan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hien.buivan@gmail.com`@`localhost` ;
CREATE USER `phuong.chau@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `phuong.chau@gmail.com`@`localhost` ;
CREATE USER `ha.chaudai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `ha.chaudai@gmail.com`@`localhost` ;
CREATE USER `son.chaudai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `son.chaudai@gmail.com`@`localhost` ;
CREATE USER `hau.cungtrong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hau.cungtrong@gmail.com`@`localhost` ;
CREATE USER `tuan.dangmai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `tuan.dangmai@gmail.com`@`localhost` ;
CREATE USER `tuyen.dangthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `tuyen.dangthanh@gmail.com`@`localhost` ;
CREATE USER `vvan.dangthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `vvan.dangthithanh@gmail.com`@`localhost` ;
CREATE USER `ngoc.daoxuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `ngoc.daoxuan@gmail.com`@`localhost` ;
CREATE USER `dang.dodinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `dang.dodinh@gmail.com`@`localhost` ;
CREATE USER `hai.dominh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hai.dominh@gmail.com`@`localhost` ;
CREATE USER `trung.duongthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `trung.duongthanh@gmail.com`@`localhost` ;
CREATE USER `tuong.hathanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `tuong.hathanh@gmail.com`@`localhost` ;
CREATE USER `huyen.hathi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `huyen.hathi@gmail.com`@`localhost` ;
CREATE USER `kieu.hathimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `kieu.hathimy@gmail.com`@`localhost` ;
CREATE USER `toan.hoanghai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `toan.hoanghai@gmail.com`@`localhost` ;
CREATE USER `lien.hoangthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `lien.hoangthi@gmail.com`@`localhost` ;
CREATE USER `thuy.hoangthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thuy.hoangthi@gmail.com`@`localhost` ;
CREATE USER `dung.hoangvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `dung.hoangvan@gmail.com`@`localhost` ;
CREATE USER `manh.hoangvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `manh.hoangvan@gmail.com`@`localhost` ;
CREATE USER `tam.huynhhuu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `tam.huynhhuu@gmail.com`@`localhost` ;
CREATE USER `tuan.huynhthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `tuan.huynhthanh@gmail.com`@`localhost` ;
CREATE USER `tram.huynhthihuyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `tram.huynhthihuyen@gmail.com`@`localhost` ;
CREATE USER `tho.huynhthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `tho.huynhthikim@gmail.com`@`localhost` ;
CREATE USER `trinh.kieuthihuyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `trinh.kieuthihuyen@gmail.com`@`localhost` ;
CREATE USER `thu.laithianh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thu.laithianh@gmail.com`@`localhost` ;
CREATE USER `kinh.lamdai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `kinh.lamdai@gmail.com`@`localhost` ;
CREATE USER `lieu.lanhthinhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `lieu.lanhthinhu@gmail.com`@`localhost` ;
CREATE USER `an.leduc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `an.leduc@gmail.com`@`localhost` ;
CREATE USER `hien.lehong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hien.lehong@gmail.com`@`localhost` ;
CREATE USER `su.lehong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `su.lehong@gmail.com`@`localhost` ;
CREATE USER `vi.lemoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `vi.lemoc@gmail.com`@`localhost` ;
CREATE USER `canh.lenguyenhong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `canh.lenguyenhong@gmail.com`@`localhost` ;
CREATE USER `vinh.lethaihoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `vinh.lethaihoang@gmail.com`@`localhost` ;
CREATE USER `thanh.lethi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thanh.lethi@gmail.com`@`localhost` ;
CREATE USER `ly.lethihai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `ly.lethihai@gmail.com`@`localhost` ;
CREATE USER `tham.lethihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `tham.lethihong@gmail.com`@`localhost` ;
CREATE USER `mo.lethituyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `mo.lethituyet@gmail.com`@`localhost` ;
CREATE USER `chan.letranquynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `chan.letranquynh@gmail.com`@`localhost` ;
CREATE USER `thanh.letranthai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thanh.letranthai@gmail.com`@`localhost` ;
CREATE USER `binh.levan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `binh.levan@gmail.com`@`localhost` ;
CREATE USER `dung.levan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `dung.levan@gmail.com`@`localhost` ;
CREATE USER `sang.levan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `sang.levan@gmail.com`@`localhost` ;
CREATE USER `vang.levan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `vang.levan@gmail.com`@`localhost` ;
CREATE USER `trinh.luongduy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `trinh.luongduy@gmail.com`@`localhost` ;
CREATE USER `nghiem.luuquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `nghiem.luuquoc@gmail.com`@`localhost` ;
CREATE USER `huong.maithi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `huong.maithi@gmail.com`@`localhost` ;
CREATE USER `cuc.ngothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `cuc.ngothi@gmail.com`@`localhost` ;
CREATE USER `vinh.nguyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `vinh.nguyen@gmail.com`@`localhost` ;
CREATE USER `phan.nguyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `phan.nguyen@gmail.com`@`localhost` ;
CREATE USER `khuong.nguyenanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `khuong.nguyenanh@gmail.com`@`localhost` ;
CREATE USER `linh.nguyenba@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `linh.nguyenba@gmail.com`@`localhost` ;
CREATE USER `ngoc.nguyenbao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `ngoc.nguyenbao@gmail.com`@`localhost` ;
CREATE USER `dat.nguyenbientan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `dat.nguyenbientan@gmail.com`@`localhost` ;
CREATE USER `thanh.nguyenchi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thanh.nguyenchi@gmail.com`@`localhost` ;
CREATE USER `duc.nguyendac@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `duc.nguyendac@gmail.com`@`localhost` ;
CREATE USER `mong.nguyendinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `mong.nguyendinh@gmail.com`@`localhost` ;
CREATE USER `hung.nguyendoangia@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hung.nguyendoangia@gmail.com`@`localhost` ;
CREATE USER `phuc.nguyenduy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `phuc.nguyenduy@gmail.com`@`localhost` ;
CREATE USER `thuy.nguyenhonhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thuy.nguyenhonhu@gmail.com`@`localhost` ;
CREATE USER `lac.nguyenhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `lac.nguyenhoang@gmail.com`@`localhost` ;
CREATE USER `duan.nguyenlengoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `duan.nguyenlengoc@gmail.com`@`localhost` ;
CREATE USER `hieu.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hieu.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER `hong.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hong.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER `thuy.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thuy.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER `ben.nguyenngocluc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `ben.nguyenngocluc@gmail.com`@`localhost` ;
CREATE USER `huong.nguyenquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `huong.nguyenquang@gmail.com`@`localhost` ;
CREATE USER `khiem.nguyentan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `khiem.nguyentan@gmail.com`@`localhost` ;
CREATE USER `be.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `be.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `chi.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `chi.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `dung.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `dung.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `duong.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `duong.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `hoang.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hoang.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `huong.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `huong.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `lan.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `lan.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `ngoc.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `ngoc.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `thuyen.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thuyen.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `diep.nguyenthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `diep.nguyenthihong@gmail.com`@`localhost` ;
CREATE USER `anh.nguyenthilan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `anh.nguyenthilan@gmail.com`@`localhost` ;
CREATE USER `truc.nguyenthimong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `truc.nguyenthimong@gmail.com`@`localhost` ;
CREATE USER `han.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `han.nguyenthingoc@gmail.com`@`localhost` ;
CREATE USER `thuy.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thuy.nguyenthingoc@gmail.com`@`localhost` ;
CREATE USER `yen.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `yen.nguyenthingoc@gmail.com`@`localhost` ;
CREATE USER `linh.nguyenthiphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `linh.nguyenthiphuong@gmail.com`@`localhost` ;
CREATE USER `nga.nguyenthiphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `nga.nguyenthiphuong@gmail.com`@`localhost` ;
CREATE USER `thuy.nguyenthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thuy.nguyenthithanh@gmail.com`@`localhost` ;
CREATE USER `ha.nguyenthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `ha.nguyenthithu@gmail.com`@`localhost` ;
CREATE USER `lien.nguyenthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `lien.nguyenthithu@gmail.com`@`localhost` ;
CREATE USER `thuy.nguyenthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thuy.nguyenthithu@gmail.com`@`localhost` ;
CREATE USER `uyen.nguyenthitu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `uyen.nguyenthitu@gmail.com`@`localhost` ;
CREATE USER `khanh.nguyentrong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `khanh.nguyentrong@gmail.com`@`localhost` ;
CREATE USER `dam.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `dam.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `phuoc.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `phuoc.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `sang.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `sang.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `toan.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `toan.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `tuong.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `tuong.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `anh.nguyenvutien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `anh.nguyenvutien@gmail.com`@`localhost` ;
CREATE USER `nguyen.nguyenxuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `nguyen.nguyenxuan@gmail.com`@`localhost` ;
CREATE USER `hoang.ngyenthuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hoang.ngyenthuy@gmail.com`@`localhost` ;
CREATE USER `khoa.phamdinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `khoa.phamdinh@gmail.com`@`localhost` ;
CREATE USER `hoa.phamdotuyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hoa.phamdotuyet@gmail.com`@`localhost` ;
CREATE USER `nguyen.phamhole@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `nguyen.phamhole@gmail.com`@`localhost` ;
CREATE USER `thao.phamphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thao.phamphuong@gmail.com`@`localhost` ;
CREATE USER `vu.phamtan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `vu.phamtan@gmail.com`@`localhost` ;
CREATE USER `dung.phamthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `dung.phamthi@gmail.com`@`localhost` ;
CREATE USER `thao.phamthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thao.phamthi@gmail.com`@`localhost` ;
CREATE USER `hieu.phamthiminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hieu.phamthiminh@gmail.com`@`localhost` ;
CREATE USER `huyen.phamthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `huyen.phamthithanh@gmail.com`@`localhost` ;
CREATE USER `tam.phamthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `tam.phamthithanh@gmail.com`@`localhost` ;
CREATE USER `an.phamthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `an.phamthithu@gmail.com`@`localhost` ;
CREATE USER `trang.phamthithuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `trang.phamthithuy@gmail.com`@`localhost` ;
CREATE USER `tuan.phananh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `tuan.phananh@gmail.com`@`localhost` ;
CREATE USER `toan.phanchi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `toan.phanchi@gmail.com`@`localhost` ;
CREATE USER `chau.phanthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `chau.phanthimy@gmail.com`@`localhost` ;
CREATE USER `ha.phanthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `ha.phanthingoc@gmail.com`@`localhost` ;
CREATE USER `chau.phanvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `chau.phanvan@gmail.com`@`localhost` ;
CREATE USER `ha.phanvokhanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `ha.phanvokhanh@gmail.com`@`localhost` ;
CREATE USER `nhut.thachminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `nhut.thachminh@gmail.com`@`localhost` ;
CREATE USER `soc.thachthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `soc.thachthi@gmail.com`@`localhost` ;
CREATE USER `thien.trandang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thien.trandang@gmail.com`@`localhost` ;
CREATE USER `toan.trankhanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `toan.trankhanh@gmail.com`@`localhost` ;
CREATE USER `dang.tranmaikhanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `dang.tranmaikhanh@gmail.com`@`localhost` ;
CREATE USER `nhut.tranminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `nhut.tranminh@gmail.com`@`localhost` ;
CREATE USER `anh.trannguyenminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `anh.trannguyenminh@gmail.com`@`localhost` ;
CREATE USER `trung.trannguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `trung.trannguyenthanh@gmail.com`@`localhost` ;
CREATE USER `quang.tranthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `quang.tranthanh@gmail.com`@`localhost` ;
CREATE USER `hanh.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hanh.tranthi@gmail.com`@`localhost` ;
CREATE USER `oanh.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `oanh.tranthi@gmail.com`@`localhost` ;
CREATE USER `van.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `van.tranthi@gmail.com`@`localhost` ;
CREATE USER `nhung.tranthikieu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `nhung.tranthikieu@gmail.com`@`localhost` ;
CREATE USER `anh.tranthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `anh.tranthikim@gmail.com`@`localhost` ;
CREATE USER `ha.tranthile@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `ha.tranthile@gmail.com`@`localhost` ;
CREATE USER `nguyet.tranthiminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `nguyet.tranthiminh@gmail.com`@`localhost` ;
CREATE USER `thu.tranthinguyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thu.tranthinguyet@gmail.com`@`localhost` ;
CREATE USER `ha.tranthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `ha.tranthithu@gmail.com`@`localhost` ;
CREATE USER `giang.trantruong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `giang.trantruong@gmail.com`@`localhost` ;
CREATE USER `mach.tranvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `mach.tranvan@gmail.com`@`localhost` ;
CREATE USER `xuan.tranvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `xuan.tranvan@gmail.com`@`localhost` ;
CREATE USER `chat.trinhthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `chat.trinhthi@gmail.com`@`localhost` ;
CREATE USER `khuong.trinhvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `khuong.trinhvan@gmail.com`@`localhost` ;
CREATE USER `trung.truonghoanhminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `trung.truonghoanhminh@gmail.com`@`localhost` ;
CREATE USER `khai.truongquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `khai.truongquang@gmail.com`@`localhost` ;
CREATE USER `an.truongvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `an.truongvan@gmail.com`@`localhost` ;
CREATE USER `hiep.truongvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hiep.truongvan@gmail.com`@`localhost` ;
CREATE USER `nhu.vanthihuynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `nhu.vanthihuynh@gmail.com`@`localhost` ;
CREATE USER `ngoc.vaybich@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `ngoc.vaybich@gmail.com`@`localhost` ;
CREATE USER `duc.voanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `duc.voanh@gmail.com`@`localhost` ;
CREATE USER `duong.vodong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `duong.vodong@gmail.com`@`localhost` ;
CREATE USER `tri.vominh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `tri.vominh@gmail.com`@`localhost` ;
CREATE USER `huy.voquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `huy.voquoc@gmail.com`@`localhost` ;
CREATE USER `linh.vothanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `linh.vothanh@gmail.com`@`localhost` ;
CREATE USER `huyen.vothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `huyen.vothi@gmail.com`@`localhost` ;
CREATE USER `phuoc.vothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `phuoc.vothi@gmail.com`@`localhost` ;
CREATE USER `yen.vothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `yen.vothi@gmail.com`@`localhost` ;
CREATE USER `ngoc.vothinhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `ngoc.vothinhu@gmail.com`@`localhost` ;
CREATE USER `hai.votuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hai.votuan@gmail.com`@`localhost` ;
CREATE USER `hau.vovan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hau.vovan@gmail.com`@`localhost` ;
CREATE USER `tam.vuduy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `tam.vuduy@gmail.com`@`localhost` ;
CREATE USER `anh.vuhung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `anh.vuhung@gmail.com`@`localhost` ;
CREATE USER `trieu.vuminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `trieu.vuminh@gmail.com`@`localhost` ;
CREATE USER `hang.vunguyenthuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hang.vunguyenthuy@gmail.com`@`localhost` ;
CREATE USER `chung.vuquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `chung.vuquoc@gmail.com`@`localhost` ;
CREATE USER `hoai.vuthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `hoai.vuthanh@gmail.com`@`localhost` ;
CREATE USER `thuan.vuthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thuan.vuthi@gmail.com`@`localhost` ;
CREATE USER `tu.vuthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `tu.vuthi@gmail.com`@`localhost` ;
CREATE USER `my.vuthiha@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `my.vuthiha@gmail.com`@`localhost` ;
CREATE USER `loan.vuthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `loan.vuthithanh@gmail.com`@`localhost` ;
CREATE USER `trang.vuthithuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `trang.vuthithuy@gmail.com`@`localhost` ;
CREATE USER `thang.vutien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `learner_role` TO `thang.vutien@gmail.com`@`localhost` ;

-- create supporter account

CREATE USER `hung.bui@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hung.bui@gmail.com`@`localhost` ;
CREATE USER `thiet.buidinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `thiet.buidinh@gmail.com`@`localhost` ;
CREATE USER `tuyen.buiduc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `tuyen.buiduc@gmail.com`@`localhost` ;
CREATE USER `kieu.buithikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `kieu.buithikim@gmail.com`@`localhost` ;
CREATE USER `dung.caovan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `dung.caovan@gmail.com`@`localhost` ;
CREATE USER `khoa.chauanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `khoa.chauanh@gmail.com`@`localhost` ;
CREATE USER `hanh.chauthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hanh.chauthi@gmail.com`@`localhost` ;
CREATE USER `duyen.chauthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `duyen.chauthihong@gmail.com`@`localhost` ;
CREATE USER `phi.cungkieu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `phi.cungkieu@gmail.com`@`localhost` ;
CREATE USER `vui.dangcong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `vui.dangcong@gmail.com`@`localhost` ;
CREATE USER `cuong.danghung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `cuong.danghung@gmail.com`@`localhost` ;
CREATE USER `ba.dangthe@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `ba.dangthe@gmail.com`@`localhost` ;
CREATE USER `tien.dangvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `tien.dangvan@gmail.com`@`localhost` ;
CREATE USER `son.daohoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `son.daohoang@gmail.com`@`localhost` ;
CREATE USER `khanh.daoquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `khanh.daoquang@gmail.com`@`localhost` ;
CREATE USER `thuong.dinhhoai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `thuong.dinhhoai@gmail.com`@`localhost` ;
CREATE USER `luyen.dinhthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `luyen.dinhthi@gmail.com`@`localhost` ;
CREATE USER `huy.dothaianh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `huy.dothaianh@gmail.com`@`localhost` ;
CREATE USER `thanh.dothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `thanh.dothi@gmail.com`@`localhost` ;
CREATE USER `huyen.dothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `huyen.dothi@gmail.com`@`localhost` ;
CREATE USER `mai.dothihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `mai.dothihong@gmail.com`@`localhost` ;
CREATE USER `lich.dovan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `lich.dovan@gmail.com`@`localhost` ;
CREATE USER `cuong.duonghung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `cuong.duonghung@gmail.com`@`localhost` ;
CREATE USER `duyen.hathihai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `duyen.hathihai@gmail.com`@`localhost` ;
CREATE USER `tien.hoangthicam@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `tien.hoangthicam@gmail.com`@`localhost` ;
CREATE USER `cuong.hoangvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `cuong.hoangvan@gmail.com`@`localhost` ;
CREATE USER `thu.huynhthicam@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `thu.huynhthicam@gmail.com`@`localhost` ;
CREATE USER `oanh.huynhthikieu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `oanh.huynhthikieu@gmail.com`@`localhost` ;
CREATE USER `phung.huynhthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `phung.huynhthikim@gmail.com`@`localhost` ;
CREATE USER `dung.huynhthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `dung.huynhthimy@gmail.com`@`localhost` ;
CREATE USER `hau.huynhvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hau.huynhvan@gmail.com`@`localhost` ;
CREATE USER `oanh.lamnhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `oanh.lamnhu@gmail.com`@`localhost` ;
CREATE USER `thien.ledinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `thien.ledinh@gmail.com`@`localhost` ;
CREATE USER `que.ledong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `que.ledong@gmail.com`@`localhost` ;
CREATE USER `truc.leminhphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `truc.leminhphuong@gmail.com`@`localhost` ;
CREATE USER `loc.lephat@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `loc.lephat@gmail.com`@`localhost` ;
CREATE USER `si.lethihoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `si.lethihoang@gmail.com`@`localhost` ;
CREATE USER `lieu.lethihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `lieu.lethihong@gmail.com`@`localhost` ;
CREATE USER `truc.lethithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `truc.lethithanh@gmail.com`@`localhost` ;
CREATE USER `phuc.luonghuu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `phuc.luonghuu@gmail.com`@`localhost` ;
CREATE USER `dien.luongquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `dien.luongquang@gmail.com`@`localhost` ;
CREATE USER `van.lythi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `van.lythi@gmail.com`@`localhost` ;
CREATE USER `nhan.ngohoai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `nhan.ngohoai@gmail.com`@`localhost` ;
CREATE USER `hung.ngoquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hung.ngoquang@gmail.com`@`localhost` ;
CREATE USER `khoa.ngoquangdang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `khoa.ngoquangdang@gmail.com`@`localhost` ;
CREATE USER `sang.ngothikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `sang.ngothikim@gmail.com`@`localhost` ;
CREATE USER `son.nguyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `son.nguyen@gmail.com`@`localhost` ;
CREATE USER `anh.nguyendinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `anh.nguyendinh@gmail.com`@`localhost` ;
CREATE USER `tan.nguyendoan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `tan.nguyendoan@gmail.com`@`localhost` ;
CREATE USER `ngan.nguyenhoaithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `ngan.nguyenhoaithanh@gmail.com`@`localhost` ;
CREATE USER `dien.nguyenhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `dien.nguyenhoang@gmail.com`@`localhost` ;
CREATE USER `long.nguyenhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `long.nguyenhoang@gmail.com`@`localhost` ;
CREATE USER `thuan.nguyenhoanggia@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `thuan.nguyenhoanggia@gmail.com`@`localhost` ;
CREATE USER `sinh.nguyenhung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `sinh.nguyenhung@gmail.com`@`localhost` ;
CREATE USER `nhu.nguyenhuynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `nhu.nguyenhuynh@gmail.com`@`localhost` ;
CREATE USER `dieu.nguyenhuynhhong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `dieu.nguyenhuynhhong@gmail.com`@`localhost` ;
CREATE USER `anh.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `anh.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER `khanh.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `khanh.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER `long.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `long.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER `nhi.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `nhi.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER `anh.nguyenngochoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `anh.nguyenngochoang@gmail.com`@`localhost` ;
CREATE USER `nguyen.nguyenngockhoi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `nguyen.nguyenngockhoi@gmail.com`@`localhost` ;
CREATE USER `tam.nguyenngocthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `tam.nguyenngocthanh@gmail.com`@`localhost` ;
CREATE USER `son.nguyenphuoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `son.nguyenphuoc@gmail.com`@`localhost` ;
CREATE USER `phi.nguyenphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `phi.nguyenphuong@gmail.com`@`localhost` ;
CREATE USER `duy.nguyenquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `duy.nguyenquang@gmail.com`@`localhost` ;
CREATE USER `huy.nguyenquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `huy.nguyenquang@gmail.com`@`localhost` ;
CREATE USER `dat.nguyenquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `dat.nguyenquoc@gmail.com`@`localhost` ;
CREATE USER `to.nguyentan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `to.nguyentan@gmail.com`@`localhost` ;
CREATE USER `hoang.nguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hoang.nguyenthanh@gmail.com`@`localhost` ;
CREATE USER `phong.nguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `phong.nguyenthanh@gmail.com`@`localhost` ;
CREATE USER `huyen.nguyenthao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `huyen.nguyenthao@gmail.com`@`localhost` ;
CREATE USER `hang.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hang.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `hue.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hue.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `luyen.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `luyen.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `nga.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `nga.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `ninh.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `ninh.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `phuong.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `phuong.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `quyen.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `quyen.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `thao.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `thao.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `thuong.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `thuong.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `yen.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `yen.nguyenthi@gmail.com`@`localhost` ;
CREATE USER `thu.nguyenthianh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `thu.nguyenthianh@gmail.com`@`localhost` ;
CREATE USER `yen.nguyenthihoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `yen.nguyenthihoang@gmail.com`@`localhost` ;
CREATE USER `hoang.nguyenthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hoang.nguyenthikim@gmail.com`@`localhost` ;
CREATE USER `thoa.nguyenthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `thoa.nguyenthikim@gmail.com`@`localhost` ;
CREATE USER `suong.nguyenthimai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `suong.nguyenthimai@gmail.com`@`localhost` ;
CREATE USER `hanh.nguyenthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hanh.nguyenthimy@gmail.com`@`localhost` ;
CREATE USER `khuyen.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `khuyen.nguyenthingoc@gmail.com`@`localhost` ;
CREATE USER `binh.nguyenthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `binh.nguyenthithanh@gmail.com`@`localhost` ;
CREATE USER `duong.nguyenthithuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `duong.nguyenthithuy@gmail.com`@`localhost` ;
CREATE USER `anh.nguyenthitram@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `anh.nguyenthitram@gmail.com`@`localhost` ;
CREATE USER `hoang.nguyenthuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hoang.nguyenthuy@gmail.com`@`localhost` ;
CREATE USER `hieu.nguyentrung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hieu.nguyentrung@gmail.com`@`localhost` ;
CREATE USER `tien.nguyentrung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `tien.nguyentrung@gmail.com`@`localhost` ;
CREATE USER `linh.nguyentuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `linh.nguyentuan@gmail.com`@`localhost` ;
CREATE USER `dau.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `dau.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `hau.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hau.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `long.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `long.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `ngon.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `ngon.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `son.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `son.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `trang.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `trang.nguyenvan@gmail.com`@`localhost` ;
CREATE USER `quang.nguyenvinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `quang.nguyenvinh@gmail.com`@`localhost` ;
CREATE USER `nhan.nguyenvy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `nhan.nguyenvy@gmail.com`@`localhost` ;
CREATE USER `phuc.phamhoai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `phuc.phamhoai@gmail.com`@`localhost` ;
CREATE USER `phuoc.phamhuu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `phuoc.phamhuu@gmail.com`@`localhost` ;
CREATE USER `khanh.phamphu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `khanh.phamphu@gmail.com`@`localhost` ;
CREATE USER `tien.phamphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `tien.phamphuong@gmail.com`@`localhost` ;
CREATE USER `kieu.phamthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `kieu.phamthi@gmail.com`@`localhost` ;
CREATE USER `huyen.phamthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `huyen.phamthimy@gmail.com`@`localhost` ;
CREATE USER `ngoc.phamtien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `ngoc.phamtien@gmail.com`@`localhost` ;
CREATE USER `nghia.phamtrong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `nghia.phamtrong@gmail.com`@`localhost` ;
CREATE USER `hien.phamvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hien.phamvan@gmail.com`@`localhost` ;
CREATE USER `nghia.phamxuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `nghia.phamxuan@gmail.com`@`localhost` ;
CREATE USER `my.phanhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `my.phanhoang@gmail.com`@`localhost` ;
CREATE USER `hien.phannguyenphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hien.phannguyenphuong@gmail.com`@`localhost` ;
CREATE USER `nguyen.phanthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `nguyen.phanthanh@gmail.com`@`localhost` ;
CREATE USER `ngoc.phanthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `ngoc.phanthi@gmail.com`@`localhost` ;
CREATE USER `no.phanthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `no.phanthi@gmail.com`@`localhost` ;
CREATE USER `vien.phungduy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `vien.phungduy@gmail.com`@`localhost` ;
CREATE USER `sen.son@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `sen.son@gmail.com`@`localhost` ;
CREATE USER `lan.tathi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `lan.tathi@gmail.com`@`localhost` ;
CREATE USER `uyen.tothihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `uyen.tothihong@gmail.com`@`localhost` ;
CREATE USER `nhi.trananh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `nhi.trananh@gmail.com`@`localhost` ;
CREATE USER `hoa.tranquynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hoa.tranquynh@gmail.com`@`localhost` ;
CREATE USER `minh.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `minh.tranthi@gmail.com`@`localhost` ;
CREATE USER `te.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `te.tranthi@gmail.com`@`localhost` ;
CREATE USER `chau.tranthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `chau.tranthihong@gmail.com`@`localhost` ;
CREATE USER `tam.tranthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `tam.tranthithanh@gmail.com`@`localhost` ;
CREATE USER `hoa.tranthithuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hoa.tranthithuan@gmail.com`@`localhost` ;
CREATE USER `trinh.tranthivan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `trinh.tranthivan@gmail.com`@`localhost` ;
CREATE USER `tuyen.tranthien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `tuyen.tranthien@gmail.com`@`localhost` ;
CREATE USER `hua.tranvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `hua.tranvan@gmail.com`@`localhost` ;
CREATE USER `song.tranvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `song.tranvan@gmail.com`@`localhost` ;
CREATE USER `oanh.tranxuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `oanh.tranxuan@gmail.com`@`localhost` ;
CREATE USER `nhi.trinhthiphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `nhi.trinhthiphuong@gmail.com`@`localhost` ;
CREATE USER `tuan.truongminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `tuan.truongminh@gmail.com`@`localhost` ;
CREATE USER `viet.truongquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `viet.truongquang@gmail.com`@`localhost` ;
CREATE USER `su.truongthiminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `supporter_role` TO `su.truongthiminh@gmail.com`@`localhost` ;

