-- CREATE USER IF NOT EXISTS 'roy'@'localhost' IDENTIFIED BY 'kimngan1704';
-- GRANT CREATE ON food_order.* TO 'roy'@'localhost';
-- GRANT ALL PRIVILEGES ON food_order.* TO 'roy'@'localhost';
-- FLUSH PRIVILEGES;

-- CREATE USER IF NOT EXISTS 'customer'@'localhost' IDENTIFIED BY 'kimngan1704';
-- GRANT CREATE ON food_order.* TO 'customer'@'localhost';

alter user 'root'@'localhost' identified with mysql_native_password by 'kimngan1704';


USE `food_order`;

DROP VIEW IF EXISTS `Customer_view`;
CREATE VIEW `Customer_view` AS
SELECT `Fname`, `Mname`, `Lname`, `BDate`, `Gender`, `Email`, C.`username`, `password`
FROM `Customer` C JOIN `Account` A ON C.`username` = A.`username`
WITH LOCAL CHECK OPTION;

DROP VIEW IF EXISTS `Co_restaurant_view`;
CREATE VIEW `Co_restaurant_view` AS
SELECT `Res_name`, `Rate`, C.`username`, `password`
FROM `Co_restaurant` C JOIN `Account` A ON C.`username` = A.`username`
WITH LOCAL CHECK OPTION;

DROP VIEW IF EXISTS `Administration_view`;
CREATE VIEW `Administration_view` AS
SELECT  Ad.`username`, `password`
FROM `Administration` Ad JOIN `Account` Ac ON Ad.`username` = Ac.`username`
WITH LOCAL CHECK OPTION;

DROP ROLE IF EXISTS `customer_role`;
CREATE ROLE `customer_role`;

GRANT SELECT, UPDATE, DELETE ON food_order.`Customer_view` TO `customer_role`;
GRANT SELECT ON food_order.`Customer` to `customer_role`;
GRANT SELECT ON food_order.`Customer_phone` to `customer_role`;
GRANT SELECT ON food_order.`Menbership` to `customer_role`;
GRANT SELECT ON food_order.`Food_type` to `customer_role`;
GRANT SELECT ON food_order.`Combo` to `customer_role`;
GRANT SELECT ON food_order.`Food_order` to `customer_role`;
GRANT SELECT ON food_order.`Food_combo` to `customer_role`;
GRANT SELECT ON food_order.`Combo_order` to `customer_role`;
GRANT SELECT ON food_order.`Food_cart` to `customer_role`;
GRANT SELECT ON food_order.`Combo_cart` to `customer_role`;
GRANT SELECT ON food_order.`Order_promotion` to `customer_role`;
GRANT SELECT ON food_order.`Coupon` to `customer_role`;
GRANT SELECT ON food_order.`Voucher` to `customer_role`;
GRANT SELECT ON food_order.`Promotion` to `customer_role`;


GRANT SELECT, INSERT, DELETE, UPDATE ON food_order.`Payment` to `customer_role`;
GRANT SELECT, INSERT, DELETE, UPDATE ON food_order.`E-wallet` to `customer_role`;
GRANT SELECT, INSERT, DELETE, UPDATE ON food_order.`Card` to `customer_role`;

DROP ROLE IF EXISTS`co_restaurant_role`;
CREATE ROLE `co_restaurant_role`;

GRANT SELECT, UPDATE, DELETE ON food_order.`Co_restaurant_view` TO `co_restaurant_role`;
GRANT SELECT ON food_order.`Co_restaurant` to `co_restaurant_role`;
GRANT SELECT ON food_order.`Co_restaurant_address` to `co_restaurant_role`;
GRANT SELECT ON food_order.`Co_restaurant_phone` to `co_restaurant_role`;
GRANT SELECT ON food_order.`Food_type` to `co_restaurant_role`;
GRANT SELECT ON food_order.`Food_order` to `co_restaurant_role`;
GRANT SELECT ON food_order.`Combo_order` to `co_restaurant_role`;
GRANT SELECT ON food_order.`Food_combo` to `co_restaurant_role`;
GRANT SELECT ON food_order.`Food_cart` to `co_restaurant_role`;
GRANT SELECT ON food_order.`Combo_cart` to `co_restaurant_role`;
GRANT SELECT ON food_order.`Order_promotion` to `co_restaurant_role`;
GRANT SELECT ON food_order.`Coupon` to `co_restaurant_role`;
GRANT SELECT ON food_order.`Voucher` to `co_restaurant_role`;
GRANT SELECT ON food_order.`Promotion` to `co_restaurant_role`;


GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Food` to `co_restaurant_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Combo` to `co_restaurant_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Promotion` to `co_restaurant_role`;


DROP ROLE IF EXISTS `administration_role`;
CREATE ROLE `administration_role`;


GRANT SELECT, UPDATE, DELETE ON food_order.`Administration_view` TO `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Customer` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Customer_phone` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Menbership` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Food_type` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Combo` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Food_order` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Food_combo` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Combo_order` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Food_cart` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Combo_cart` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Order_promotion` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Coupon` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Voucher` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Promotion` to `administration_role`;
GRANT SELECT, INSERT, DELETE, UPDATE ON food_order.`Payment` to `administration_role`;
GRANT SELECT, INSERT, DELETE, UPDATE ON food_order.`E-wallet` to `administration_role`;
GRANT SELECT, INSERT, DELETE, UPDATE ON food_order.`Card` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Co_restaurant` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Co_restaurant_address` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Co_restaurant_phone` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Food_order` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Food` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Combo` to `administration_role`;
GRANT SELECT, INSERT, UPDATE, DELETE ON food_order.`Promotion` to `administration_role`;


-- CREATE USER IF NOT EXISTS and grant role
CREATE USER IF NOT EXISTS `minh.buikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `minh.buikim@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thu.buithi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `thu.buithi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `anh.buituan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `anh.buituan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thanh.buixuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `thanh.buixuan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hien.caophamthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hien.caophamthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ngan.caothihai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `ngan.caothihai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `guan.chaiyeong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `guan.chaiyeong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thanh.chaudai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `thanh.chaudai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `truc.danghoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `truc.danghoang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hanh.dangthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hanh.dangthimy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `du.daocao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `du.daocao@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hai.daothien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hai.daothien@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phong.dinhtran@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `phong.dinhtran@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nam.dohoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `nam.dohoang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nguyen.dongocthao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `nguyen.dongocthao@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `khuyen.dothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `khuyen.dothi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ngan.dothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `ngan.dothi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `van.doanthituyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `van.doanthituyet@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `truong.doanxuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `truong.doanxuan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `cuong.duongquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `cuong.duongquoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuan.hodang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `thuan.hodang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hao.hohuu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hao.hohuu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thanh.hothithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `thanh.hothithu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trinh.hoangnukieu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `trinh.hoangnukieu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `anh.hoangquynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `anh.hoangquynh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tung.hoangthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `tung.hoangthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `sinh.huadieptruong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `sinh.huadieptruong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tat.huynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `tat.huynh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nghia.huynhngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `nghia.huynhngoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hung.huynhnhat@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hung.huynhnhat@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `sac.huynhtang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `sac.huynhtang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dung.huynhthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `dung.huynhthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `diep.huynhthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `diep.huynhthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nga.huynhthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `nga.huynhthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `to.huynhthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `to.huynhthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuy.huynhthicam@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `thuy.huynhthicam@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `lan.huynhvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `lan.huynhvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `minh.huynhvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `minh.huynhvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trang.khauthiyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `trang.khauthiyen@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tuyet.lamnhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `tuyet.lamnhu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phuong.lemy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `phuong.lemy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `danh.lethanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `danh.lethanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ty.lethihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `ty.lethihong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hoa.luongthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hoa.luongthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dung.lyanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `dung.lyanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `lam.lyson@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `lam.lyson@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `koko.mady@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `koko.mady@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nguyen.ngohuynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `nguyen.ngohuynh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dung.ngoquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `dung.ngoquang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `vinh.ngothe@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `vinh.ngothe@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trong.nguyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `trong.nguyen@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ninh.nguyendoan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `ninh.nguyendoan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `duong.nguyenduc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `duong.nguyenduc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `uyen.nguyengiamai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `uyen.nguyengiamai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `duy.nguyenhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `duy.nguyenhoang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nam.nguyenhong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `nam.nguyenhong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `cuong.nguyenhung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `cuong.nguyenhung@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ngan.nguyenkim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `ngan.nguyenkim@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hunh.nguyenmanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hunh.nguyenmanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `duc.nguyenminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `duc.nguyenminh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `quang.nguyenminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `quang.nguyenminh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuan.nguyenminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `thuan.nguyenminh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuc.nguyenminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `thuc.nguyenminh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hoa.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hoa.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `qui.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `qui.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `long.nguyenphi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `long.nguyenphi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thao.nguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `thao.nguyenthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tung.nguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `tung.nguyenthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `long.nguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `long.nguyenthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dung.nguyenthe@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `dung.nguyenthe@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `an.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `an.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `diem.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `diem.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ha.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `ha.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `linh.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `linh.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `luan.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `luan.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `man.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `man.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nguyet.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `nguyet.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `oanh.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `oanh.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuy.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `thuy.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dao.nguyenthianh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `dao.nguyenthianh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hoa.nguyenthicong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hoa.nguyenthicong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dieu.nguyenthihanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `dieu.nguyenthihanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ly.nguyenthihoai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `ly.nguyenthihoai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `huong.nguyenthihoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `huong.nguyenthihoang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dung.nguyenthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `dung.nguyenthikim@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phuong.nguyenthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `phuong.nguyenthikim@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `oanh.nguyenthile@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `oanh.nguyenthile@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ly.nguyenthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `ly.nguyenthimy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `bang.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `bang.nguyenthingoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `em.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `em.nguyenthingoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tuyet.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `tuyet.nguyenthingoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hien.nguyenthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hien.nguyenthithu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thao.nguyenthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `thao.nguyenthithu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trang.nguyenthithuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `trang.nguyenthithuy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `mai.nguyenthituyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `mai.nguyenthituyet@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hien.nguyenthuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hien.nguyenthuong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `lam.nguyentung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `lam.nguyentung@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `vy.nguyentuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `vy.nguyentuong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `bay.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `bay.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `cam.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `cam.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `canh.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `canh.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ha.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `ha.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hien.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hien.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tan.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `tan.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tho.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `tho.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tien.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `tien.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `cuong.nguyenviet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `cuong.nguyenviet@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hieu.nuyenthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hieu.nuyenthihong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `vuong.pham@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `vuong.pham@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phong.phamduy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `phong.phamduy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `linh.phamhoaikhanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `linh.phamhoaikhanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `khanh.phamhong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `khanh.phamhong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `khoi.phammanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `khoi.phammanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `son.phamngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `son.phamngoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `luat.phamquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `luat.phamquang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `oanh.phamthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `oanh.phamthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `xuan.phamthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `xuan.phamthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `loan.phamthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `loan.phamthihong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hanh.phamthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hanh.phamthithu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `loan.phamthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `loan.phamthithu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dao.phamthitruc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `dao.phamthitruc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `anh.phanhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `anh.phanhoang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phong.phanthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `phong.phanthithu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hau.phantrung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hau.phantrung@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hieu.phanvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hieu.phanvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `long.phunghoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `long.phunghoang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nguyen.phuongcao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `nguyen.phuongcao@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trang.tannhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `trang.tannhu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hue.tongthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hue.tongthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ngoc.tranbao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `ngoc.tranbao@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `sang.tranbao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `sang.tranbao@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hung.trancong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hung.trancong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `chien.trandinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `chien.trandinh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `duong.trandinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `duong.trandinh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tri.tranhuu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `tri.tranhuu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `vuong.trankim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `vuong.trankim@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ngan.tranngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `ngan.tranngoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `van.trannhat@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `van.trannhat@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `triet.tranongminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `triet.tranongminh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ha.tranphamthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `ha.tranphamthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `linh.tranquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `linh.tranquoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `bup.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `bup.tranthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hien.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hien.tranthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thu.tranthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `thu.tranthihong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hoa.tranthoai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `hoa.tranthoai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `anh.trantuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `anh.trantuan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nhat.tranvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `nhat.tranvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trinh\.truongquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `trinh\.truongquang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `that.truongthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `that.truongthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dung.truongtien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `co_restaurant_role` TO `dung.truongtien@gmail.com`@`localhost` ;

-- create account for learner

CREATE USER IF NOT EXISTS `son.buidai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `son.buidai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nam.buithihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `nam.buithihong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `duong.buithithuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `duong.buithithuy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `mai.buithitruc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `mai.buithitruc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trinh.buithituyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `trinh.buithituyet@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ky.buitrung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `ky.buitrung@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `kiet.buituan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `kiet.buituan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hien.buivan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hien.buivan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phuong.chau@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `phuong.chau@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ha.chaudai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `ha.chaudai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `son.chaudai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `son.chaudai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hau.cungtrong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hau.cungtrong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tuan.dangmai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `tuan.dangmai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tuyen.dangthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `tuyen.dangthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `vvan.dangthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `vvan.dangthithanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ngoc.daoxuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `ngoc.daoxuan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dang.dodinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `dang.dodinh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hai.dominh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hai.dominh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trung.duongthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `trung.duongthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tuong.hathanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `tuong.hathanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `huyen.hathi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `huyen.hathi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `kieu.hathimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `kieu.hathimy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `toan.hoanghai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `toan.hoanghai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `lien.hoangthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `lien.hoangthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuy.hoangthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thuy.hoangthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dung.hoangvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `dung.hoangvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `manh.hoangvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `manh.hoangvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tam.huynhhuu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `tam.huynhhuu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tuan.huynhthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `tuan.huynhthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tram.huynhthihuyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `tram.huynhthihuyen@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tho.huynhthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `tho.huynhthikim@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trinh.kieuthihuyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `trinh.kieuthihuyen@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thu.laithianh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thu.laithianh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `kinh.lamdai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `kinh.lamdai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `lieu.lanhthinhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `lieu.lanhthinhu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `an.leduc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `an.leduc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hien.lehong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hien.lehong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `su.lehong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `su.lehong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `vi.lemoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `vi.lemoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `canh.lenguyenhong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `canh.lenguyenhong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `vinh.lethaihoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `vinh.lethaihoang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thanh.lethi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thanh.lethi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ly.lethihai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `ly.lethihai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tham.lethihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `tham.lethihong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `mo.lethituyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `mo.lethituyet@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `chan.letranquynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `chan.letranquynh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thanh.letranthai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thanh.letranthai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `binh.levan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `binh.levan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dung.levan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `dung.levan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `sang.levan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `sang.levan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `vang.levan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `vang.levan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trinh.luongduy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `trinh.luongduy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nghiem.luuquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `nghiem.luuquoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `huong.maithi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `huong.maithi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `cuc.ngothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `cuc.ngothi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `vinh.nguyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `vinh.nguyen@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phan.nguyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `phan.nguyen@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `khuong.nguyenanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `khuong.nguyenanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `linh.nguyenba@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `linh.nguyenba@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ngoc.nguyenbao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `ngoc.nguyenbao@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dat.nguyenbientan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `dat.nguyenbientan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thanh.nguyenchi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thanh.nguyenchi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `duc.nguyendac@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `duc.nguyendac@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `mong.nguyendinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `mong.nguyendinh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hung.nguyendoangia@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hung.nguyendoangia@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phuc.nguyenduy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `phuc.nguyenduy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuy.nguyenhonhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thuy.nguyenhonhu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `lac.nguyenhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `lac.nguyenhoang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `duan.nguyenlengoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `duan.nguyenlengoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hieu.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hieu.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hong.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hong.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuy.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thuy.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ben.nguyenngocluc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `ben.nguyenngocluc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `huong.nguyenquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `huong.nguyenquang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `khiem.nguyentan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `khiem.nguyentan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `be.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `be.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `chi.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `chi.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dung.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `dung.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `duong.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `duong.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hoang.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hoang.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `huong.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `huong.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `lan.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `lan.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ngoc.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `ngoc.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuyen.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thuyen.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `diep.nguyenthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `diep.nguyenthihong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `anh.nguyenthilan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `anh.nguyenthilan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `truc.nguyenthimong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `truc.nguyenthimong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `han.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `han.nguyenthingoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuy.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thuy.nguyenthingoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `yen.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `yen.nguyenthingoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `linh.nguyenthiphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `linh.nguyenthiphuong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nga.nguyenthiphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `nga.nguyenthiphuong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuy.nguyenthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thuy.nguyenthithanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ha.nguyenthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `ha.nguyenthithu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `lien.nguyenthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `lien.nguyenthithu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuy.nguyenthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thuy.nguyenthithu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `uyen.nguyenthitu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `uyen.nguyenthitu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `khanh.nguyentrong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `khanh.nguyentrong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dam.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `dam.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phuoc.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `phuoc.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `sang.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `sang.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `toan.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `toan.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tuong.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `tuong.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `anh.nguyenvutien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `anh.nguyenvutien@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nguyen.nguyenxuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `nguyen.nguyenxuan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hoang.ngyenthuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hoang.ngyenthuy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `khoa.phamdinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `khoa.phamdinh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hoa.phamdotuyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hoa.phamdotuyet@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nguyen.phamhole@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `nguyen.phamhole@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thao.phamphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thao.phamphuong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `vu.phamtan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `vu.phamtan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dung.phamthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `dung.phamthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thao.phamthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thao.phamthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hieu.phamthiminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hieu.phamthiminh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `huyen.phamthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `huyen.phamthithanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tam.phamthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `tam.phamthithanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `an.phamthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `an.phamthithu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trang.phamthithuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `trang.phamthithuy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tuan.phananh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `tuan.phananh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `toan.phanchi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `toan.phanchi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `chau.phanthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `chau.phanthimy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ha.phanthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `ha.phanthingoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `chau.phanvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `chau.phanvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ha.phanvokhanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `ha.phanvokhanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nhut.thachminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `nhut.thachminh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `soc.thachthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `soc.thachthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thien.trandang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thien.trandang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `toan.trankhanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `toan.trankhanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dang.tranmaikhanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `dang.tranmaikhanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nhut.tranminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `nhut.tranminh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `anh.trannguyenminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `anh.trannguyenminh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trung.trannguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `trung.trannguyenthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `quang.tranthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `quang.tranthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hanh.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hanh.tranthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `oanh.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `oanh.tranthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `van.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `van.tranthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nhung.tranthikieu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `nhung.tranthikieu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `anh.tranthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `anh.tranthikim@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ha.tranthile@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `ha.tranthile@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nguyet.tranthiminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `nguyet.tranthiminh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thu.tranthinguyet@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thu.tranthinguyet@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ha.tranthithu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `ha.tranthithu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `giang.trantruong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `giang.trantruong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `mach.tranvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `mach.tranvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `xuan.tranvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `xuan.tranvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `chat.trinhthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `chat.trinhthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `khuong.trinhvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `khuong.trinhvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trung.truonghoanhminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `trung.truonghoanhminh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `khai.truongquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `khai.truongquang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `an.truongvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `an.truongvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hiep.truongvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hiep.truongvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nhu.vanthihuynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `nhu.vanthihuynh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ngoc.vaybich@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `ngoc.vaybich@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `duc.voanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `duc.voanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `duong.vodong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `duong.vodong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tri.vominh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `tri.vominh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `huy.voquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `huy.voquoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `linh.vothanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `linh.vothanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `huyen.vothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `huyen.vothi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phuoc.vothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `phuoc.vothi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `yen.vothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `yen.vothi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ngoc.vothinhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `ngoc.vothinhu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hai.votuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hai.votuan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hau.vovan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hau.vovan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tam.vuduy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `tam.vuduy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `anh.vuhung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `anh.vuhung@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trieu.vuminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `trieu.vuminh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hang.vunguyenthuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hang.vunguyenthuy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `chung.vuquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `chung.vuquoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hoai.vuthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `hoai.vuthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuan.vuthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thuan.vuthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tu.vuthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `tu.vuthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `my.vuthiha@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `my.vuthiha@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `loan.vuthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `loan.vuthithanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trang.vuthithuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `trang.vuthithuy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thang.vutien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `customer_role` TO `thang.vutien@gmail.com`@`localhost` ;

-- create supporter account

CREATE USER IF NOT EXISTS `hung.bui@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hung.bui@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thiet.buidinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `thiet.buidinh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tuyen.buiduc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `tuyen.buiduc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `kieu.buithikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `kieu.buithikim@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dung.caovan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `dung.caovan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `khoa.chauanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `khoa.chauanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hanh.chauthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hanh.chauthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `duyen.chauthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `duyen.chauthihong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phi.cungkieu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `phi.cungkieu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `vui.dangcong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `vui.dangcong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `cuong.danghung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `cuong.danghung@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ba.dangthe@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `ba.dangthe@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tien.dangvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `tien.dangvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `son.daohoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `son.daohoang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `khanh.daoquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `khanh.daoquang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuong.dinhhoai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `thuong.dinhhoai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `luyen.dinhthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `luyen.dinhthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `huy.dothaianh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `huy.dothaianh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thanh.dothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `thanh.dothi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `huyen.dothi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `huyen.dothi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `mai.dothihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `mai.dothihong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `lich.dovan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `lich.dovan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `cuong.duonghung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `cuong.duonghung@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `duyen.hathihai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `duyen.hathihai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tien.hoangthicam@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `tien.hoangthicam@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `cuong.hoangvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `cuong.hoangvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thu.huynhthicam@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `thu.huynhthicam@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `oanh.huynhthikieu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `oanh.huynhthikieu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phung.huynhthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `phung.huynhthikim@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dung.huynhthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `dung.huynhthimy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hau.huynhvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hau.huynhvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `oanh.lamnhu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `oanh.lamnhu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thien.ledinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `thien.ledinh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `que.ledong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `que.ledong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `truc.leminhphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `truc.leminhphuong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `loc.lephat@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `loc.lephat@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `si.lethihoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `si.lethihoang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `lieu.lethihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `lieu.lethihong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `truc.lethithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `truc.lethithanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phuc.luonghuu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `phuc.luonghuu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dien.luongquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `dien.luongquang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `van.lythi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `van.lythi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nhan.ngohoai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `nhan.ngohoai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hung.ngoquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hung.ngoquang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `khoa.ngoquangdang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `khoa.ngoquangdang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `sang.ngothikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `sang.ngothikim@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `son.nguyen@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `son.nguyen@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `anh.nguyendinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `anh.nguyendinh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tan.nguyendoan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `tan.nguyendoan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ngan.nguyenhoaithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `ngan.nguyenhoaithanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dien.nguyenhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `dien.nguyenhoang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `long.nguyenhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `long.nguyenhoang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuan.nguyenhoanggia@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `thuan.nguyenhoanggia@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `sinh.nguyenhung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `sinh.nguyenhung@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nhu.nguyenhuynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `nhu.nguyenhuynh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dieu.nguyenhuynhhong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `dieu.nguyenhuynhhong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `anh.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `anh.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `khanh.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `khanh.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `long.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `long.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nhi.nguyenngoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `nhi.nguyenngoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `anh.nguyenngochoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `anh.nguyenngochoang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nguyen.nguyenngockhoi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `nguyen.nguyenngockhoi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tam.nguyenngocthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `tam.nguyenngocthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `son.nguyenphuoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `son.nguyenphuoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phi.nguyenphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `phi.nguyenphuong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `duy.nguyenquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `duy.nguyenquang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `huy.nguyenquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `huy.nguyenquang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dat.nguyenquoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `dat.nguyenquoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `to.nguyentan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `to.nguyentan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hoang.nguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hoang.nguyenthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phong.nguyenthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `phong.nguyenthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `huyen.nguyenthao@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `huyen.nguyenthao@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hang.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hang.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hue.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hue.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `luyen.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `luyen.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nga.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `nga.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ninh.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `ninh.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phuong.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `phuong.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `quyen.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `quyen.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thao.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `thao.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thuong.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `thuong.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `yen.nguyenthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `yen.nguyenthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thu.nguyenthianh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `thu.nguyenthianh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `yen.nguyenthihoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `yen.nguyenthihoang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hoang.nguyenthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hoang.nguyenthikim@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `thoa.nguyenthikim@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `thoa.nguyenthikim@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `suong.nguyenthimai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `suong.nguyenthimai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hanh.nguyenthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hanh.nguyenthimy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `khuyen.nguyenthingoc@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `khuyen.nguyenthingoc@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `binh.nguyenthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `binh.nguyenthithanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `duong.nguyenthithuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `duong.nguyenthithuy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `anh.nguyenthitram@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `anh.nguyenthitram@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hoang.nguyenthuy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hoang.nguyenthuy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hieu.nguyentrung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hieu.nguyentrung@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tien.nguyentrung@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `tien.nguyentrung@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `linh.nguyentuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `linh.nguyentuan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `dau.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `dau.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hau.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hau.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `long.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `long.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ngon.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `ngon.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `son.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `son.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trang.nguyenvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `trang.nguyenvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `quang.nguyenvinh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `quang.nguyenvinh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nhan.nguyenvy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `nhan.nguyenvy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phuc.phamhoai@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `phuc.phamhoai@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `phuoc.phamhuu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `phuoc.phamhuu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `khanh.phamphu@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `khanh.phamphu@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tien.phamphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `tien.phamphuong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `kieu.phamthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `kieu.phamthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `huyen.phamthimy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `huyen.phamthimy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ngoc.phamtien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `ngoc.phamtien@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nghia.phamtrong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `nghia.phamtrong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hien.phamvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hien.phamvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nghia.phamxuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `nghia.phamxuan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `my.phanhoang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `my.phanhoang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hien.phannguyenphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hien.phannguyenphuong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nguyen.phanthanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `nguyen.phanthanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `ngoc.phanthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `ngoc.phanthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `no.phanthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `no.phanthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `vien.phungduy@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `vien.phungduy@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `sen.son@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `sen.son@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `lan.tathi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `lan.tathi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `uyen.tothihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `uyen.tothihong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nhi.trananh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `nhi.trananh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hoa.tranquynh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hoa.tranquynh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `minh.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `minh.tranthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `te.tranthi@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `te.tranthi@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `chau.tranthihong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `chau.tranthihong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tam.tranthithanh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `tam.tranthithanh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hoa.tranthithuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hoa.tranthithuan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `trinh.tranthivan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `trinh.tranthivan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tuyen.tranthien@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `tuyen.tranthien@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `hua.tranvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `hua.tranvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `song.tranvan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `song.tranvan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `oanh.tranxuan@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `oanh.tranxuan@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `nhi.trinhthiphuong@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `nhi.trinhthiphuong@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `tuan.truongminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `tuan.truongminh@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `viet.truongquang@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `viet.truongquang@gmail.com`@`localhost` ;
CREATE USER IF NOT EXISTS `su.truongthiminh@gmail.com`@`localhost` IDENTIFIED BY '123456' ;
GRANT `administration_role` TO `su.truongthiminh@gmail.com`@`localhost` ;


